import Navigation from "../components/navigation"

export const metadata = {
  title: 'test',                        //html 에서 title 
  description: 'Generated by Next.js',  // <meta name="description" content="Generated by Next.js">
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
